### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by hyb965149985** [amjltc295/Free-Form-Video-Inpainting#27]
Hi, authors. Thanks for your splendid works.
when i run train.py with test mode i get this error:

Traceback (most recent call last):
  File "F:\py\Free-Form-Video-Inpainting-master\src\trainer\trainer.py", line 426, in evaluate_test_set
    output_root_dir=output_root_dir, epoch=epoch)
  File "F:\py\Free-Form-Video-Inpainting-master\src\trainer\trainer.py", line 98, in _evaluate_data_loader
    for batch_idx, data in enumerate(data_loader):
  File "E:\Anaconda3\envs\opn\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "E:\Anaconda3\envs\opn\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "E:\Anaconda3\envs\opn\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "E:\Anaconda3\envs\opn\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Anaconda3\envs\opn\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\Anaconda3\envs\opn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Anaconda3\envs\opn\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "F:\py\Free-Form-Video-Inpainting-master\src\utils\directory_IO.py", line 54, in __getattr__
    f"{attr} not in root_dir_names {self.output_root_dirs}")
KeyError: "__getstate__ not in root_dir_names {'masked_frames': '../VOS_resized2\\\\masked_frames', 'result_frames': '../VO
S_resized2\\\\result_frames', 'optical_flows': '../VOS_resized2\\\\optical_flows'}"
--Call--
> e:\anaconda3\envs\opn\lib\multiprocessing\util.py(182)__call__()
-> def __call__(self, wr=None,
(Pdb) Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\opn\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda3\envs\opn\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by amjltc295** [comment]
1. Did you follow the instructions to install the packages?
2. What is the command you ran? 
3. Is it on Windows? The code has not been tested on Windows and if it's an OS issue you have to solve it yourself

**Comment by hyb965149985** [comment]
Thank you for your patience when I put  "n_ gpu": 0 , "num_ Workers ": 0,  it works.
It is on Windows.

**Comment by hyb965149985** [comment]
Thank you for your patience when I put "n_ gpu": 0 , "num_ Workers ": 0, it works.
It is on Windows.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ya-Liang Chang (Allen)"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 凌晨3:54
收件人: "amjltc295/Free-Form-Video-Inpainting"<Free-Form-Video-Inpainting@noreply.github.com&gt;; 
抄送: "霍一博"<965149985@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [amjltc295/Free-Form-Video-Inpainting] Running error (#27)



Did you follow the instructions to install the packages?
 What is the command you ran?
 Is it on Windows? The code has not been tested on Windows and if it's an OS issue you have to solve it yourself
