### ISSUE TITLE
Connection Time Out: Link not Working

### ISSUE THREAD

**Issue by WinnieLaugh** [amjltc295/Free-Form-Video-Inpainting#28]
Hi, Thanks for your wonderful work!

I was trying to train the network with your code, but it seems the link in the code does not work any more. The error I got is:

Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main(config, args.resume, args.output_root_dir, args.pretrained_path)
  File "train.py", line 103, in main
    pretrained_path=pretrained_path
  File "/media/wenhua/disk_wenhua/workspace/Free-Form-Video-Inpainting/src/trainer/trainer.py", line 53, in __init__
    init_i3d_model()
  File "/media/wenhua/disk_wenhua/workspace/Free-Form-Video-Inpainting/src/evaluate.py", line 44, in init_i3d_model
    urllib.request.urlretrieve('http://www.cmlab.csie.ntu.edu.tw/~zhe2325138/i3d_rgb_imagenet.pt', i3d_model_weight)
  File "/home/wenhua/anaconda3/envs/free_form_video_inpainting/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/wenhua/anaconda3/envs/free_form_video_inpainting/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/wenhua/anaconda3/envs/free_form_video_inpainting/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/wenhua/anaconda3/envs/free_form_video_inpainting/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/wenhua/anaconda3/envs/free_form_video_inpainting/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/wenhua/anaconda3/envs/free_form_video_inpainting/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/wenhua/anaconda3/envs/free_form_video_inpainting/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

Thanks!

**Comment by amjltc295** [comment]
I think the work station is under maintenance. @Nash2325138 could you update the link?

**Comment by MaureenZOU** [comment]
https://drive.google.com/file/d/14eRdVxCeO4Q90YPyTJGDh96dV8XVIlzz/view?usp=sharing
Feel free to use my version  ; )

**Comment by Nash2325138** [comment]
Sorry for the missing link. Our department is under renovation, and its network is down, making this link unreachable.

Because our I3D implementation is from this repo: https://github.com/piergiaj/pytorch-i3d, you can download the exact trained weights from https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_imagenet.pt to replace the one downloaded at http://www.cmlab.csie.ntu.edu.tw/~zhe2325138/i3d_rgb_imagenet.pt 
Just rename the file as 'i3d_rgb_imagenet.pt' and put it under 'libs/model_weights/' to solve this problem.

Otherwise you can wait for the network of our department to go back to normal, but the finish date of the renovation is really unclear.
