### ISSUE TITLE
training problem 

### ISSUE THREAD

**Issue by hank19960918** [amjltc295/Free-Form-Video-Inpainting#31]
Thanks for your wonderful  sharing.
I try to train the model by the dataset you provided but I met some error.
There is a file here "FaceForensics\FaceForensics\Train\videos\mx7Yv0zAtAk_0_nQcD9LbDm1Y_0" is empty.
The following is the error message.  

[2020-07-30 06:08:52,315] {trainer.py:384} INFO - Epoch: 1 [0/854  (0%)] loss_total: 1.860, BT: 2.97s
[2020-07-30 06:10:41,876] {trainer.py:384} INFO - Epoch: 1 [80/854  (9%)] loss_total: 2.344, BT: 2.73s
[2020-07-30 06:12:31,386] {trainer.py:384} INFO - Epoch: 1 [160/854  (19%)] loss_total: 1.278, BT: 2.73s
[2020-07-30 06:14:20,886] {trainer.py:384} INFO - Epoch: 1 [240/854  (28%)] loss_total: 2.026, BT: 2.73s
[2020-07-30 06:16:07,748] {dataset.py:115} WARNING - len frames 0 reader 0 < sample_length 32 dir ../dataset/FaceForensics/Train/videos/mx7Yv0zAtAk_0_nQcD9LbDm1Y_0
[2020-07-30 06:16:10,395] {trainer.py:384} INFO - Epoch: 1 [320/854  (37%)] loss_total: 1.831, BT: 2.73s
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main(config, args.resume, args.output_root_dir, args.pretrained_path)
  File "train.py", line 112, in main
    trainer.train()
  File "/storage/Free-Form-Video-Inpainting-master/src/base/base_trainer.py", line 98, in train
    result = self._train_epoch(epoch)
  File "/storage/Free-Form-Video-Inpainting-master/src/trainer/trainer.py", line 319, in _train_epoch
    for batch_idx, data in enumerate(self.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/storage/Free-Form-Video-Inpainting-master/src/data_loader/dataset.py", line 171, in __getitem__
    return self._process_vds(vds)
  File "/storage/Free-Form-Video-Inpainting-master/src/data_loader/dataset.py", line 120, in _process_vds
    gt_frames = self._transform(gt_frames)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/storage/Free-Form-Video-Inpainting-master/src/data_loader/transform.py", line 22, in __call__
    w, h = img_group[0].size
IndexError: list index out of range

Thanks for your help.

**Comment by caimaomao315** [comment]
I also encountered the same problem as you, did you solve it?
